_target_: torch.utils.data.DataLoader
dataset: 
  _target_: dataset.CelebAHQDataset
  path_data: data/datasets/celebahq/imgs
  path_labels: data/datasets/celebahq/labels.csv
  n_samples: ${exp.n_samples}
batch_size: ${exp.n_unique}
num_workers: 0