_target_: torch.utils.data.DataLoader
dataset: 
  _target_: dataset.CheXpertDataset
  path_data: data/datasets/chexpert/imgs
  path_labels: data/datasets/chexpert/labels.csv
  n_samples: ${exp.n_samples}
batch_size: ${exp.n_unique}
num_workers: 0